---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: custom-cosmic
# description will be included in the image's metadata
description: This is my personal OS image.
alt-tags:
  - stable
  - latest

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/cosmic-atomic-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: script
    scripts:
      - nix.sh
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - micro
      - starship
      - tailscale
      # drivers
      - system-config-printer
      - hplip
      - ghostscript
      - gvfs
      - gvfs-client
      - gvfs-fuse
      - gvfs-mtp
      - gvfs-smb
      - https://updates.safing.io/latest/linux_amd64/packages/Portmaster-2.0.23-1.x86_64.rpm
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - htop

  - type: default-flatpaks@v1
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - com.brave.Browser
        - io.github.flattool.Warehouse
        - io.github.dvlv.boxbuddyrs
        - it.mijorus.gearlever
        - dev.edfloreshz.CosmicTweaks
        - org.onlyoffice.desktopeditors
        - org.gnome.Loupe
        - dev.deedles.Trayscale
        - org.gpodder.gpodder
        - io.github.mpobaschnig.Vaults
        - org.virt_manager.virt-manager
        - org.virt_manager.virt_manager.Extension.Qemu
      remove:
        - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: systemd
    system:
      enabled:
        - tailscaled.service
        - portmaster.service
        - cups.service
  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry
